services:
  mongo:
    image: mongo:8.0.1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 27017
    ports: 
      - "27017:27017" 

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    expose:
      - 1080
      - 1025

  api:
    build:
      context: .
      dockerfile: document.e2e.Dockerfile
    env_file:
      - env-example
    depends_on:
      - mongo
      - maildev
