name: Telemedicine Platform API CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # <database-document-block>
      - name: Run e2e tests for NestJS with Mongoose
        id: document
        run: docker compose -f docker-compose.document.ci.yaml --env-file env-example -p ci-document up --build --exit-code-from api || echo "Error encountered during Docker Compose up."

      - name: Copy prod.log from container to host
        if: ${{ failure() && steps.document.conclusion == 'failure' }}
        run: docker cp ci-document-api-1:/usr/src/app/prod.log .
      # </database-document-block>

      - name: Upload prod.log to artifacts for debugging
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: prod-logs
          path: prod.log
